# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Auto Crawler

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install selenium
        python -m pip install bs4
        python -m pip install multiprocessing
        python -m pip install pandas
        python -m pip install webdriver_manager
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Chromdriver
      run: |
    - name: Install Chromdriver
      run: |
    - name: Install Chromdriver
      run: |        
    - name: Run Crawler
      run: |
        python danawa_crawling.py
      env:
        MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Commits
      run: |
        git config --local user.email "qorwhdghk12@gmail.com"
        git config --local user.name "qor0530"
        git add --all
        git commit -m "Bot - Auto Crawl | $(date -d '+9 hour' +'%Y-%m-%d %H:%M:%S')"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: ${{ secrets.GITHUB_TOKEN }}
